require 'uri'
require 'highline/import'
require 'spreadsheet'
require 'roo'

def write_xls(name, sheets)
  xls =  Spreadsheet.new
  sheets.each do |title, cells|
    sheet = xls.create_worksheet
    sheet.name = title
    cells.each_with_index  do |row, i|
      row.each_with_index do |val, j|
        sheet[i,j] = val
      end
    end
  end
  
  xls.write name
end

def open_xls(name)
  if name.include?(' ')
    puts "文件名[#{name}]含有空格"
    return
  end
  unless File.exists?(name)
    puts "文件[#{name}]不存在"
    return
  end

  Roo::Spreadsheet.open name
end

namespace :janeliar do
  desc 'Janeliar Stocks'
  task :stocks do
    f1 = ask('对照表文件？')

    xls1= open_xls 'tmp/Janeliastocks.xls' # todo
    unless xls1
      next
    end

    f2 = ask('操作表文件？')
    xls2= open_xls 'tmp/Janeliar_Gal4_line_summary_04012015.xlsx' # todo
    unless xls2
      next
    end

    ok = ask('确定要继续么？(y/n)') { |q| q.default='n' }
    next unless ok == 'y'



    cells = []

    xls2.sheet(xls2.sheets.first).each do |row2|
      puts "正在处理#{row2[0].to_s}"

      xls1.sheet(xls1.sheets.first).each do |row1|
        if row1[3].to_s.start_with?("P{GM#{row2[0]}")
          cells << [row2[0].to_s, row1[0].to_i]
          break
        end
      end
    end

    write_xls 'tmp/result.xls', {'Sheet 1'=>cells}
  end
end